# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install poetry==1.7.1
      - poetry export --only docs --without-hashes -o requirements.txt

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py
